version: '3.5'
services: 
  ##
  # https://www.postgresql.org/
  #
  postgres:
    container_name: gitgrok_postgres
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
